### ISSUE TITLE
[BE / API Gateway] 웹 소켓 연결 테스트 실패

### ISSUE THREAD

**Issue by Tae-Hyeon** [STOVE-Milk/steam-clone#30]
``` yml
- id: robby-http-svc
  uri: http://localhost:8210/
  predicates:
    - Path=/library/info/**
- id: robby-ws-svc
  uri: ws://localhost:8210/
  predicates:
    - Path=/library/**
```
